### ISSUE TITLE
Reconsider the name

### ISSUE THREAD

**Issue by omeid** [cztomsik/graffiti#117]
The project looks very interesting and has potential to be a serious but much lightweight contender to the likes of Electron, so thanks for working on this.

However, the name is a bit unfortunate as the word _stain_ generally doesn't have a positive connotation, it implies dirty, unclean or even corrupt. I for one am personally a bit reluctant to suggest _let's use stain for this project_.

I don't have any strong suggestion for a name, but something more positive would be better for the project. 

Here are 2 suggestions:

- prime (as in, primitive ui components)
- elements (ui elements)
- react-render

**Comment by cztomsik** [comment]
The name is not final, however, it's much better than the original name (`node-webrender`) which caused a lot of confusion so it had to be changed.

You are right about the connotation, I agree and I'd also prefer something positive.

`prime` sounds good but as with all good names, they are usually taken or they could cause confusion with existing projects. But yeah, I will think about it, and really thanks for reaching me.

and about `react-*` this is not good either, as this project is not 100% focused on react, I'd also like to support vue & svelte in the future

**Comment by omeid** [comment]
Alright, thanks for the response. Glad you're considering other UI libraries as well, I am keen to see how things pan out. Good luck!

**Comment by cztomsik** [comment]
name changed, more news to come soon! :)

**Comment by omeid** [comment]
It is definitely a better name than stain, but I am not sure if you are aware of the link between graffiti and vandalism, I thought I would mention it just as a heads up.
