### ISSUE TITLE
Failed to load OpenGL driver

### ISSUE THREAD

**Issue by shanoaice** [cztomsik/graffiti#157]
Rust panics when I tried to run examples:
`thread '<unnamed>' panicked at 'load fn glGetProgramiv in lib "opengl32.dll"', src\platform.rs:31:13`

I'm unsure what has gone wrong because I am sure the opengl32.dll is present in my System32 directory, and I've done a system-wide mesa deploy.

Hardware/System:
- Graphics: `Intel UHD 620`
- CPU: `Intel Core i5-8265U`
- System: `Windows 10 20H2 build 19042.662`

**Comment by cztomsik** [comment]
hm, that's super-strange (no idea how to help, sorry)

**Comment by cztomsik** [comment]
should be fixed now (but we still have some layout issues to resolve in the new version)
