### ISSUE TITLE
[Idea] Publish on npm

### ISSUE THREAD

**Issue by denyncrawford** [cztomsik/graffiti#163]
Would it be possible to publish the module to npm so it can be imported with skypack on Deno? I'm triying to run an example out of the box importing the module directly from github and it is not possible since the imports don't have the file extension, and running it with the `--no-check` flag is not working, so to solve this and support Deno remote imports without using the .ts file extensions you can just publish the module so it is available for node on npm and deno trough skypack without making any changes.

**Comment by JoCat** [comment]
At the moment it is not working stable, so most likely there is no package on npm

**Comment by cztomsik** [comment]
related to #169

**Comment by cztomsik** [comment]
NPM is not planned in the near future.
