### ISSUE TITLE
can run graffity usingin deno on ubuntu 20.04 ? and how ?

### ISSUE THREAD

**Issue by elycheikhsmail** [cztomsik/graffiti#169]

**Comment by cztomsik** [comment]
- only deno 1.8.7 is supported for now (you need to downgrade with `deno upgrade --version 1.8.7`)
- you need rust & cargo (installed from rustup.rs, the one from apt might be too old)
- then it should be just `git clone` + `npm i && deno run -Ar --unstable --no-check --inspect lib/cli.js run examples/counter.html`

BTW: discord might be better place to ask for this https://discord.gg/zQwyzFb

**Comment by elycheikhsmail** [comment]
thank you. isn't possible to avoid npm i ?

**Comment by cztomsik** [comment]
you would need to somehow call esbuild to generate bundles (`index.js` and `worker.js`)
other than that you just need to execute `cargo build` in the `libgraffiti` directory and that should be all what's needed

in the future I'd like to provide those bundles (and prebuilt binaries) via github releases so you'd only need a github url to pointing to that release but it's not done yet and I have other priorities right now
