### ISSUE TITLE
Deno-Deploy

### ISSUE THREAD

**Issue by nhrones** [cztomsik/graffiti#172]
Any plans to support/enhance for Deploy. I see a great fit.
If you get the time, read the full https://github.com/nhrones/DenoDice#readme

**Comment by cztomsik** [comment]
hey, not until https://github.com/denoland/deno/pull/11152 lands
deno basically removed their whole plugin api lately so we need to wait

**Comment by nhrones** [comment]
Thanks, This is a very impressive package you've assembled.
