### ISSUE TITLE
basic implementation of VirtualizedList 

### ISSUE THREAD

**Issue by twop** [cztomsik/graffiti#29]
documentation: https://facebook.github.io/react-native/docs/virtualizedlist

Basic idea is to connect several critical pieces in one place:
1) onLayout callback from yoga
2) calculate high of all items
3) Listen to onScroll event
4) Taking into account the view port fill that up with void and dynamically add/remove content.

Can be a really nice playground for event system, because it touches all parts of the system

**Comment by cztomsik** [comment]
will happen in user-space (`react-window` and similar libs for respective frameworks)
