### ISSUE TITLE
add vue support

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/graffiti#42]
this is tracking issue so that it's obvious we want to support vue when it gets released

I think it should be possible (to certain extent) to just recompile our `*.tsx` components with Vue (vnodes are not compatible, but jsx might be, if we restrict ourselves to functions and hooks)

ETA: ~March 2019

EDIT: It should work now but it's not tested/supported.

**Comment by f3l1x** [comment]
I would ❤️ to see that. We're building desktop apps with NW.js (mainly) / Electron, but based on Vue.js. This looks promising.

**Comment by cztomsik** [comment]
hey, thx for reaching out! I hope vue3 gets released soon so we can start working on that. BTW: we have a discord now, feel free to [join us](https://discord.gg/zQwyzFb)

**Comment by niutech** [comment]
Why can't you use Vue 2 [JSX](https://vuejs.org/v2/guide/render-function.html#JSX) syntax with Graffiti now?

**Comment by cztomsik** [comment]
@niutech I think it should be possible - and I think once I merge `innerHTML` it should work even with classic inline templates (it's using innerHTML to clear elements).

Feel free to try it but I'll probably wait with examples until Vue 3 is released since it's really close now.

**Comment by cztomsik** [comment]
should work in next release
